# Generated by Django 5.0.6 on 2024-05-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
