# Generated by Django 5.0.6 on 2024-05-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderunit_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
